"""New column in Printer

Revision ID: 04fa0416ff44
Revises: ccefd85755a8
Create Date: 2022-11-01 18:19:48.848247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fa0416ff44'
down_revision = 'ccefd85755a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('location_now', sa.String(length=50), nullable=False))
    op.add_column('printer', sa.Column('learning_campus_now', sa.String(length=25), nullable=False))
    op.add_column('printer', sa.Column('cabinet_now', sa.String(length=10), nullable=False))
    op.drop_column('printer', 'cabinet')
    op.drop_column('printer', 'learning_campus')
    op.drop_column('printer', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('location', sa.VARCHAR(length=50), nullable=True))
    op.add_column('printer', sa.Column('learning_campus', sa.VARCHAR(length=25), nullable=False))
    op.add_column('printer', sa.Column('cabinet', sa.VARCHAR(length=10), nullable=True))
    op.drop_column('printer', 'cabinet_now')
    op.drop_column('printer', 'learning_campus_now')
    op.drop_column('printer', 'location_now')
    # ### end Alembic commands ###
