"""empty message

Revision ID: 19153309aa4f
Revises: 5cfe58a2d3e6
Create Date: 2024-03-05 13:03:53.001816

"""
import sys

from alembic import op
import sqlalchemy as sa
from script4 import get_data, set_data

# revision identifiers, used by Alembic.
revision = '19153309aa4f'
down_revision = '5cfe58a2d3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_WorkList')
    with op.batch_alter_table('WorkList', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=False,
                              existing_server_default=sa.text("'ИП0000'"))

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.alter_column('work_done',
                              existing_type=sa.BOOLEAN(),
                              type_=sa.Integer(),
                              existing_nullable=False)

    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.alter_column('work_done',
                              existing_type=sa.BOOLEAN(),
                              type_=sa.Integer(),
                              existing_nullable=False)
    data = get_data()
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=50),
                              type_=sa.Integer(),
                              nullable=True)
        batch_op.create_foreign_key(None, 'ListModelsPrinter', ['name'], ['id'])
    set_data(data)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(length=50),
                              nullable=False)
        batch_op.alter_column('work_done',
                              existing_type=sa.Integer(),
                              type_=sa.BOOLEAN(),
                              existing_nullable=False)

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.alter_column('work_done',
                              existing_type=sa.Integer(),
                              type_=sa.BOOLEAN(),
                              existing_nullable=False)

    with op.batch_alter_table('WorkList', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=100),
                              nullable=True,
                              existing_server_default=sa.text("'ИП0000'"))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_responsible_for_buildings', sa.BOOLEAN(), nullable=True))

    op.create_table('_alembic_tmp_User',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=35), nullable=False),
                    sa.Column('is_boss', sa.BOOLEAN(), nullable=False),
                    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
