"""удаление таблиц issuance и brought

Revision ID: 3be570023cc9
Revises: 50609ad96891
Create Date: 2023-05-07 19:43:55.721300

"""
from alembic import op
import sqlalchemy as sa
from script import main_func


# revision identifiers, used by Alembic.
revision = '3be570023cc9'
down_revision = '50609ad96891'
branch_labels = None
depends_on = None


def upgrade():
    main_func()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CartridgeIssuance')
    op.drop_table('PrinterIssuance')
    op.drop_table('BroughtACartridge')
    op.drop_table('BroughtAPrinter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BroughtAPrinter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=15), nullable=False),
    sa.Column('learning_campus', sa.VARCHAR(length=35), nullable=False),
    sa.Column('cabinet', sa.VARCHAR(length=15), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=40), nullable=False),
    sa.Column('printer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BroughtACartridge',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=15), nullable=False),
    sa.Column('learning_campus', sa.VARCHAR(length=35), nullable=False),
    sa.Column('cabinet', sa.VARCHAR(length=15), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=40), nullable=False),
    sa.Column('cartridge_number_id', sa.INTEGER(), nullable=True),
    sa.Column('printer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_number_id'], ['cartridges.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PrinterIssuance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=15), nullable=True),
    sa.Column('learning_campus', sa.VARCHAR(length=35), nullable=True),
    sa.Column('cabinet', sa.VARCHAR(length=15), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=40), nullable=True),
    sa.Column('printer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CartridgeIssuance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=15), nullable=True),
    sa.Column('learning_campus', sa.VARCHAR(length=35), nullable=True),
    sa.Column('cabinet', sa.VARCHAR(length=15), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=40), nullable=True),
    sa.Column('cartridge_number_id', sa.INTEGER(), nullable=True),
    sa.Column('printer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_number_id'], ['cartridges.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
