"""empty message

Revision ID: 46747d99fd88
Revises: 19153309aa4f
Create Date: 2024-03-05 13:27:18.152416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46747d99fd88'
down_revision = '19153309aa4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_Buildings')
    with op.batch_alter_table('Buildings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Buildings_building'), ['building'])

    with op.batch_alter_table('Division', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_Division_division'), ['division'])

    with op.batch_alter_table('ListModels', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ListModels_model'), ['model'])

    with op.batch_alter_table('ListModelsPrinter', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ListModelsPrinter_model'), ['model'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_responsible_for_buildings', sa.Boolean(), server_default="1", nullable=False))

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_cartridges_number'), ['number'])

    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_printer_num_inventory'), ['num_inventory'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_printer_num_inventory'), type_='unique')

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cartridges_number'), type_='unique')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('is_responsible_for_buildings')

    with op.batch_alter_table('ListModelsPrinter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ListModelsPrinter_model'), type_='unique')

    with op.batch_alter_table('ListModels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ListModels_model'), type_='unique')

    with op.batch_alter_table('Division', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Division_division'), type_='unique')

    with op.batch_alter_table('Buildings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_Buildings_building'), type_='unique')

    op.create_table('_alembic_tmp_Buildings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('building', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building', name='uq_Buildings_building')
    )
    # ### end Alembic commands ###
