"""New column in Printer1

Revision ID: 4c783a15546b
Revises: 04fa0416ff44
Create Date: 2022-11-01 18:20:33.193730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c783a15546b'
down_revision = '04fa0416ff44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printer', 'location')
    op.drop_column('printer', 'learning_campus')
    op.drop_column('printer', 'cabinet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('cabinet', sa.VARCHAR(length=10), nullable=True))
    op.add_column('printer', sa.Column('learning_campus', sa.VARCHAR(length=25), nullable=False))
    op.add_column('printer', sa.Column('location', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
