"""empty message

Revision ID: 5cfe58a2d3e6
Revises: 9620af59e0a2
Create Date: 2024-01-25 15:59:33.396649

"""
from alembic import op
import sqlalchemy as sa
from script3 import setup


# revision identifiers, used by Alembic.
revision = '5cfe58a2d3e6'
down_revision = '9620af59e0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ListModelsPrinter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    with op.batch_alter_table('WorkList', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'ИП0000'"))

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.alter_column('work_done',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.alter_column('work_done',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###
    setup()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.alter_column('work_done',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.alter_column('work_done',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('WorkList', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'ИП0000'"))

    op.drop_table('ListModelsPrinter')
    # ### end Alembic commands ###
