"""empty message

Revision ID: 6cf9a8a148c0
Revises: 
Create Date: 2023-04-21 17:07:34.921200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf9a8a148c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Buildings', ['building'])
    op.create_unique_constraint(None, 'Division', ['division'])
    op.create_unique_constraint(None, 'ListModels', ['model'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ListModels', type_='unique')
    op.drop_constraint(None, 'Division', type_='unique')
    op.drop_constraint(None, 'Buildings', type_='unique')
    # ### end Alembic commands ###
