"""empty message

Revision ID: 8a0af0a31178
Revises: acfae038bce5
Create Date: 2023-05-03 20:13:44.378396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0af0a31178'
down_revision = 'acfae038bce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refills', sa.Integer(), nullable=True))
        batch_op.drop_column('refills_left')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refills_left', sa.INTEGER(), nullable=True))
        batch_op.drop_column('refills')

    # ### end Alembic commands ###
