"""empty message

Revision ID: acfae038bce5
Revises: 50609ad96891
Create Date: 2023-05-01 13:33:23.596425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfae038bce5'
down_revision = '50609ad96891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refills_left', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.drop_column('refills_left')

    # ### end Alembic commands ###
