"""empty message

Revision ID: da49b86b376c
Revises: 957fd8d9c801
Create Date: 2023-05-17 18:27:40.927945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da49b86b376c'
down_revision = '957fd8d9c801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=15), nullable=False))

    with op.batch_alter_table('cartridges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=15), nullable=False))

    # ### end Alembic commands ###
