"""empty message

Revision ID: f6f0c3fafff6
Revises: 
Create Date: 2023-04-26 18:51:18.758517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f0c3fafff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AllWorksCartridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AllWorksPrinters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building')
    )
    op.create_table('Division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('division')
    )
    op.create_table('ListModels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model')
    )
    op.create_table('ListsOfContracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_contract', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dn', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('is_boss', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('efficiency', sa.Boolean(), nullable=False),
    sa.Column('work_done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('num_inventory', sa.String(length=50), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('location_now', sa.String(length=50), nullable=False),
    sa.Column('learning_campus_now', sa.String(length=25), nullable=False),
    sa.Column('cabinet_now', sa.String(length=10), nullable=False),
    sa.Column('efficiency', sa.Boolean(), nullable=False),
    sa.Column('work_done', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_inventory')
    )
    op.create_table('AllHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('cartridge_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BroughtACartridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=False),
    sa.Column('learning_campus', sa.String(length=35), nullable=False),
    sa.Column('cabinet', sa.String(length=15), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('cartridge_number_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_number_id'], ['cartridges.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BroughtAPrinter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=False),
    sa.Column('learning_campus', sa.String(length=35), nullable=False),
    sa.Column('cabinet', sa.String(length=15), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CartridgeIssuance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=True),
    sa.Column('learning_campus', sa.String(length=35), nullable=True),
    sa.Column('cabinet', sa.String(length=15), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=True),
    sa.Column('cartridge_number_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_number_id'], ['cartridges.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CheckLists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_check', sa.DateTime(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('list_of_contracts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_of_contracts_id'], ['ListsOfContracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PrinterIssuance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=15), nullable=True),
    sa.Column('learning_campus', sa.String(length=35), nullable=True),
    sa.Column('cabinet', sa.String(length=15), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReceptionFromARefueling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('cartridge_number_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_number_id'], ['cartridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ReceptionFromARepairing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Refueling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('cartridge_number_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_number_id'], ['cartridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Repair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('cartridges_id', sa.Integer(), nullable=True),
    sa.Column('ListModels_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ListModels_id'], ['ListModels.id'], ),
    sa.ForeignKeyConstraint(['cartridges_id'], ['cartridges.id'], )
    )
    op.create_table('WorkList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('date_work', sa.DateTime(), nullable=False),
    sa.Column('check_lists_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_lists_id'], ['CheckLists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WorkListsCartridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=True),
    sa.Column('cartridge_id', sa.Integer(), nullable=True),
    sa.Column('work_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], ),
    sa.ForeignKeyConstraint(['work_list'], ['WorkList.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WorkListsPrinters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('work_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['work_list'], ['WorkList.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WorksPricesCartridges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('all_works_cartridges_id', sa.Integer(), nullable=True),
    sa.Column('work_lists_cartridges_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_works_cartridges_id'], ['AllWorksCartridges.id'], ),
    sa.ForeignKeyConstraint(['work_lists_cartridges_id'], ['WorkListsCartridges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WorksPricesPrinters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('all_works_printers_id', sa.Integer(), nullable=True),
    sa.Column('work_lists_printers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_works_printers_id'], ['AllWorksPrinters.id'], ),
    sa.ForeignKeyConstraint(['work_lists_printers_id'], ['WorkListsPrinters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WorksPricesPrinters')
    op.drop_table('WorksPricesCartridges')
    op.drop_table('WorkListsPrinters')
    op.drop_table('WorkListsCartridges')
    op.drop_table('WorkList')
    op.drop_table('association')
    op.drop_table('Repair')
    op.drop_table('Refueling')
    op.drop_table('ReceptionFromARepairing')
    op.drop_table('ReceptionFromARefueling')
    op.drop_table('PrinterIssuance')
    op.drop_table('CheckLists')
    op.drop_table('CartridgeIssuance')
    op.drop_table('BroughtAPrinter')
    op.drop_table('BroughtACartridge')
    op.drop_table('AllHistory')
    op.drop_table('printer')
    op.drop_table('cartridges')
    op.drop_table('User')
    op.drop_table('ListsOfContracts')
    op.drop_table('ListModels')
    op.drop_table('Division')
    op.drop_table('Buildings')
    op.drop_table('AllWorksPrinters')
    op.drop_table('AllWorksCartridges')
    # ### end Alembic commands ###
